[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    # 파서 정의 파일의 경로
    Parsers_File parsers.conf
    # tail 플러그인의 다중 파싱 버그 방지 및 구조 유지
    DB           /var/log/app/fluent-bit-tail.db

[INPUT]
    Name             tail
    # Spring Boot에서 생성하는 JSON 로그 파일의 컨테이너 내부 경로
    Path             /var/log/app/*.log
    Parser           json_log
    # 이 데이터 스트림에 붙일 태그명 (라우팅용 바코드 역할)
    Tag              platform.backend
    Refresh_Interval 5
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On

[FILTER]
    Name         record_modifier
    Match        *
    Record       hostname ${HOSTNAME}
    Remove_key   log

# 운영 환경
# [OUTPUT]
#     Name            kinesis_firehose
#     Match           *
#     region          ap-northeast-2
#     delivery_stream your-firehose-stream-name

[OUTPUT]
    Name   stdout
    Match  *
