-- ==========================================
-- bank_terms: terms_content 컬럼 추가
-- ==========================================
ALTER TABLE bank_terms
    ADD COLUMN terms_content LONGTEXT COMMENT 'HTML 약관 본문 (iframe srcDoc 렌더링용)';

-- ==========================================
-- 심사용 약관 HTML 본문 시드
-- ==========================================
UPDATE bank_terms SET terms_content = '<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><style>body{font-family:sans-serif;padding:16px;font-size:13px;line-height:1.7;color:#333}h2{font-size:15px;border-bottom:1px solid #ddd;padding-bottom:8px;margin-bottom:16px}h3{font-size:13px;margin-top:16px}p{margin:6px 0}ul{padding-left:20px}</style></head><body><h2>개인신용정보 수집·이용·제공 동의서</h2><p>우리피산 주식회사(이하 "회사")는 대출 심사를 위하여 아래와 같이 귀하의 개인신용정보를 수집·이용·제공하고자 합니다.</p><h3>제1조 (수집·이용 목적)</h3><p>대출 상품 심사, 계약 체결 및 이행, 금융사고 조사·예방</p><h3>제2조 (수집·이용 항목)</h3><ul><li>성명, 주민등록번호, 연락처</li><li>소득 및 재직 정보</li><li>금융거래 정보 (계좌번호, 잔액 등)</li></ul><h3>제3조 (보유 및 이용 기간)</h3><p>수집·이용 목적 달성 시까지, 관련 법령에 따른 보존 기간</p><h3>제4조 (동의 거부 권리)</h3><p>귀하는 개인신용정보 수집·이용에 대한 동의를 거부할 권리가 있습니다. 다만, 동의 거부 시 대출 서비스 제공이 불가합니다.</p><p style="margin-top:24px;color:#555">본 동의서의 내용을 충분히 숙지하였으며, 이에 동의합니다.</p></body></html>'
WHERE terms_code = 'CREDIT_INFO_AGREE';

UPDATE bank_terms SET terms_content = '<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><style>body{font-family:sans-serif;padding:16px;font-size:13px;line-height:1.7;color:#333}h2{font-size:15px;border-bottom:1px solid #ddd;padding-bottom:8px;margin-bottom:16px}h3{font-size:13px;margin-top:16px}p{margin:6px 0}ul{padding-left:20px}</style></head><body><h2>NICE 신용정보 조회 동의서</h2><p>대출 심사를 위해 NICE평가정보 주식회사에 귀하의 신용정보 조회를 의뢰합니다.</p><h3>제1조 (조회 기관)</h3><p>NICE평가정보 주식회사 (www.nicepay.co.kr)</p><h3>제2조 (조회 목적)</h3><p>대출 신청 심사 및 한도 산정</p><h3>제3조 (조회 항목)</h3><ul><li>신용점수 및 신용등급</li><li>대출·카드 보유 현황</li><li>연체 및 채무 불이행 이력</li><li>공공정보 (세금 체납, 소송 등)</li></ul><h3>제4조 (조회 기간)</h3><p>동의일로부터 3개월 이내</p><h3>제5조 (동의 거부 권리)</h3><p>귀하는 신용정보 조회 동의를 거부할 수 있으나, 거부 시 대출 심사가 불가합니다.</p><p style="margin-top:24px;color:#555">위 내용에 동의합니다.</p></body></html>'
WHERE terms_code = 'NICE_CREDIT_INQUIRY';

UPDATE bank_terms SET terms_content = '<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><style>body{font-family:sans-serif;padding:16px;font-size:13px;line-height:1.7;color:#333}h2{font-size:15px;border-bottom:1px solid #ddd;padding-bottom:8px;margin-bottom:16px}h3{font-size:13px;margin-top:16px}p{margin:6px 0}ul{padding-left:20px}</style></head><body><h2>서류 징구 및 보관 동의서</h2><p>우리피산 주식회사는 대출 심사 및 계약 이행을 위하여 아래 서류를 수집·보관합니다.</p><h3>제1조 (징구 서류)</h3><ul><li>주민등록증 사본 또는 신분증</li><li>재직증명서 또는 사업자등록증</li><li>소득확인서류 (근로소득원천징수영수증, 건강보험료 납부확인서 등)</li></ul><h3>제2조 (보관 목적)</h3><p>대출 계약 이행, 분쟁 해결, 법령 준수</p><h3>제3조 (보관 기간)</h3><p>대출 원리금 완제 후 5년 또는 관련 법령에서 정한 기간</p><h3>제4조 (폐기)</h3><p>보관 기간 만료 후 개인정보보호법에 따라 안전하게 폐기합니다.</p><p style="margin-top:24px;color:#555">위 내용에 동의합니다.</p></body></html>'
WHERE terms_code = 'DOCUMENT_COLLECT';

-- ==========================================
-- 계약용 약관 HTML 본문 시드
-- ==========================================
UPDATE bank_terms SET terms_content = '<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><style>body{font-family:sans-serif;padding:16px;font-size:13px;line-height:1.7;color:#333}h2{font-size:15px;border-bottom:1px solid #ddd;padding-bottom:8px;margin-bottom:16px}h3{font-size:13px;margin-top:16px}p{margin:6px 0}ul{padding-left:20px}</style></head><body><h2>대출 기본 약관</h2><p>본 약관은 우리피산 주식회사(이하 "회사")와 대출 고객(이하 "고객") 간의 대출 계약에 관한 기본 사항을 규정합니다.</p><h3>제1조 (대출금 지급)</h3><p>회사는 대출 계약 체결 후 고객이 지정한 계좌로 대출금을 지급합니다.</p><h3>제2조 (이자 납부)</h3><p>고객은 매월 지정된 상환일에 원리금을 납부합니다. 연체 시 연체 이율이 적용됩니다.</p><h3>제3조 (기한 이익 상실)</h3><p>다음 각 호에 해당하는 경우 기한 이익이 상실됩니다.</p><ul><li>원리금 2회 이상 연속 미납</li><li>타 금융기관 채무 연체 6개월 이상</li><li>파산 또는 회생 신청</li></ul><h3>제4조 (계약 해지)</h3><p>고객은 언제든지 잔여 원금 전액 상환으로 계약을 해지할 수 있습니다. 이 경우 중도상환수수료가 부과될 수 있습니다.</p><h3>제5조 (개인정보 처리)</h3><p>계약 이행을 위해 수집된 개인정보는 관련 법령에 따라 처리됩니다.</p><p style="margin-top:24px;color:#555">본 약관의 내용에 동의합니다.</p></body></html>'
WHERE terms_code = 'LOAN_CONTRACT_BASIC';

UPDATE bank_terms SET terms_content = '<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><style>body{font-family:sans-serif;padding:16px;font-size:13px;line-height:1.7;color:#333}h2{font-size:15px;border-bottom:1px solid #ddd;padding-bottom:8px;margin-bottom:16px}h3{font-size:13px;margin-top:16px}p{margin:6px 0}table{width:100%;border-collapse:collapse;margin:12px 0}th,td{border:1px solid #ddd;padding:8px;font-size:12px}th{background:#f5f5f5}</style></head><body><h2>대출 상품 설명서</h2><p>본 설명서는 「금융소비자 보호에 관한 법률」에 따라 대출 상품의 핵심 정보를 안내합니다.</p><h3>제1조 (상품 개요)</h3><table><tr><th>구분</th><th>내용</th></tr><tr><td>상품명</td><td>우리피산 신용대출</td></tr><tr><td>대출 금리</td><td>연 4.5% ~ 12.0% (고정 금리)</td></tr><tr><td>대출 한도</td><td>100만원 ~ 1억원</td></tr><tr><td>대출 기간</td><td>12개월 ~ 60개월</td></tr><tr><td>상환 방식</td><td>원리금 균등분할상환</td></tr></table><h3>제2조 (금리 결정 기준)</h3><p>신용점수, 소득, 직업, 금융거래 실적 등을 종합 심사하여 개인별 금리를 산정합니다.</p><h3>제3조 (총 비용)</h3><p>이자 외 인지세, 저당권 설정 비용 등이 발생할 수 있습니다. 상세 내용은 계약서를 확인하세요.</p><h3>제4조 (위험 고지)</h3><p>소득·지출 변동 시 상환 부담이 증가할 수 있습니다. 금리 상승 위험은 고정 금리 적용으로 방지됩니다.</p><p style="margin-top:24px;color:#555">본 설명서의 내용을 충분히 숙지하였습니다.</p></body></html>'
WHERE terms_code = 'LOAN_PRODUCT_TERMS';

UPDATE bank_terms SET terms_content = '<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><style>body{font-family:sans-serif;padding:16px;font-size:13px;line-height:1.7;color:#333}h2{font-size:15px;border-bottom:1px solid #ddd;padding-bottom:8px;margin-bottom:16px}h3{font-size:13px;margin-top:16px}p{margin:6px 0}ul{padding-left:20px}</style></head><body><h2>금리 변동 위험 고지서</h2><p>본 상품은 고정 금리로 운용되나, 아래 사항에 대해 충분히 이해하시기 바랍니다.</p><h3>제1조 (고정 금리 적용)</h3><p>대출 계약 시 산정된 금리는 대출 기간 전체에 걸쳐 고정 적용됩니다. 시장 금리 변동과 무관하게 동일한 이자율이 유지됩니다.</p><h3>제2조 (고정 금리의 특성)</h3><ul><li><strong>장점</strong>: 시장 금리 상승 시 추가 이자 부담 없음</li><li><strong>단점</strong>: 시장 금리 하락 시 상대적으로 높은 금리 유지</li></ul><h3>제3조 (유의사항)</h3><p>고정 금리 선택 시 중도 상환 또는 금리 재산정을 원할 경우 중도상환수수료가 발생합니다.</p><p>장기 대출의 경우 금리 환경 변화에 따른 상대적 비용 차이가 발생할 수 있습니다.</p><h3>제4조 (금리 관련 분쟁)</h3><p>금리 산정 방법 및 적용에 이의가 있는 경우 금융감독원 금융민원 포털(www.fcsc.kr)에 분쟁조정을 신청하실 수 있습니다.</p><p style="margin-top:24px;color:#555">위 고지 내용을 충분히 이해하였습니다.</p></body></html>'
WHERE terms_code = 'INTEREST_RATE_RISK';

UPDATE bank_terms SET terms_content = '<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><style>body{font-family:sans-serif;padding:16px;font-size:13px;line-height:1.7;color:#333}h2{font-size:15px;border-bottom:1px solid #ddd;padding-bottom:8px;margin-bottom:16px}h3{font-size:13px;margin-top:16px}p{margin:6px 0}table{width:100%;border-collapse:collapse;margin:12px 0}th,td{border:1px solid #ddd;padding:8px;font-size:12px}th{background:#f5f5f5}</style></head><body><h2>중도상환수수료 안내</h2><p>대출 계약 기간 이전에 원금 전부 또는 일부를 상환하는 경우 아래와 같이 중도상환수수료가 부과됩니다.</p><h3>제1조 (수수료율)</h3><table><tr><th>상환 시기</th><th>수수료율</th></tr><tr><td>대출 실행 후 1년 이내</td><td>1.5%</td></tr><tr><td>대출 실행 후 1~2년</td><td>1.0%</td></tr><tr><td>대출 실행 후 2~3년</td><td>0.5%</td></tr><tr><td>대출 실행 후 3년 초과</td><td>면제</td></tr></table><h3>제2조 (수수료 계산 방법)</h3><p>중도상환수수료 = 중도상환 원금 × 수수료율 × (잔여 기간 / 총 대출 기간)</p><h3>제3조 (수수료 면제 조건)</h3><ul><li>대출 만기 3개월 이내 상환 시</li><li>자동이체 등록 후 3년 이상 정상 납부 고객</li><li>관련 법령에 의한 면제 사유 해당 시</li></ul><h3>제4조 (수수료 납부 방법)</h3><p>중도 상환 시 수수료는 상환 원금과 함께 납부합니다.</p><p style="margin-top:24px;color:#555">위 안내 내용을 충분히 숙지하였습니다.</p></body></html>'
WHERE terms_code = 'EARLY_REPAYMENT_FEE';
