server:
  port: 8080 # 은행 코어 서버 포트

spring:
  application:
    name: bank

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  batch:
    jdbc:
      initialize-schema: always
      platform: mysql
    job:
      enabled: false

# MyBatis 설정
mybatis:
  # 1. 실제 SQL이 적힌 XML 파일들이 위치할 경로
  mapper-locations: classpath:mapper/**/*.xml

  # 2. XML에서 DTO 클래스명만 짧게 쓰기 위한 패키지 스캔 경로
  type-aliases-package: com.woorifisan.bank

  configuration:
    # 3. DB의 스네이크 케이스(account_no)를 자바의 카멜 케이스(accountNo)로 자동 변환
    map-underscore-to-camel-case: true
    # 4. 파라미터가 null일 때 발생하는 에러 방지
    jdbc-type-for-null: null

# 로깅 설정 (개발 중에 쿼리문을 콘솔에서 확인하기 위함)
logging:
  level:
    # 우리 패키지 하위에서 실행되는 MyBatis 쿼리와 파라미터를 Debug 모드로 출력
    com.woorifisan.bank: debug


