plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.14'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.google.cloud.tools.jib' version '3.4.1'
}

def buildNumber = System.getenv('BUILD_NUMBER') ?: 'latest'

jib {
	from {
		// 베이스 이미지 (가벼운 alpine 추천)
		image = 'eclipse-temurin:17-jre-alpine'
	}
	to {
		// 사설 저장소 주소와 이미지 이름
		image = 'aransword/platform_backend'

		tags = [buildNumber, 'latest'].unique()
	}
	container {
		// 스프링 부트 기본 포트 설정
		ports = ['8080']
		// JVM 옵션 등 추가 가능
		jvmFlags = ['-Xms512m', '-Xmx512m']
	}
}

group = 'com.woorifisan'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
	maven { url 'https://repo.spring.io/milestone' }
}

ext {
	set('datasourceMicrometerVersion', "1.4.1")
	set('springAiVersion', "1.0.0")
}

dependencies {
	// Validation
	implementation 'org.springframework.boot:spring-boot-starter-validation'

//	implementation platform("org.springframework.ai:spring-ai-bom:1.0.0")
	implementation 'io.github.cdimascio:dotenv-java:3.0.0'

	// Web
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

	// MyBatis + MySQL
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.5'
	runtimeOnly 'com.mysql:mysql-connector-j'

	// Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

	// JWS / mTLS
    implementation 'com.nimbusds:nimbus-jose-jwt:9.40'

	// Spring AI — Gemini + Qdrant
//	implementation 'org.springframework.ai:spring-ai-starter-model-vertex-ai-gemini'
//	implementation 'org.springframework.ai:spring-ai-starter-vector-store-qdrant'

	// Batch
	implementation 'org.springframework.boot:spring-boot-starter-batch'

	// Actuator + Prometheus + DB 메트릭
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'io.micrometer:micrometer-registry-prometheus'
	implementation 'net.ttddyy.observation:datasource-micrometer-spring-boot'

	// Logback JSON (Fluent Bit)
    implementation 'net.logstash.logback:logstash-logback-encoder:7.4'

	// Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
	
	// Test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'io.projectreactor:reactor-test'
	testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:3.0.5'
	testImplementation 'org.springframework.batch:spring-batch-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

dependencyManagement {
	imports {
		mavenBom "net.ttddyy.observation:datasource-micrometer-bom:${datasourceMicrometerVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
