pipeline {
    agent any

    environment {
        // Docker Hub ID와 리포지토리 이름
        DOCKERHUB_REPO = "aransword/monitoring_backend"
        DOCKERHUB_CREDENTIALS_ID = "DOCKERHUB_CREDENTIALS" // Jenkins에 등록한 ID (PAT 사용)
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Hello') {
            steps {
                echo 'Platform backend'
                echo "변경된 파일 목록: ${changed_files}"
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & SonarQube Analysis') {
            steps {
                dir('monitoring/backend') {
                    withSonarQubeEnv('Monitor-Backend-Sonar') {
                        sh 'chmod +x gradlew'
                        // 빌드와 분석
                        // sh './gradlew clean build sonar'
                    }
                }
            }
        }

        // stage('Quality Gate') {
        //     steps {
        //         // Quality Gate 대기
        //         timeout(time: 5, unit: 'MINUTES') {
        //             waitForQualityGate abortPipeline: true
        //         }
        //     }
        // }

        stage('Jib Build & Push to Docker Hub') {
            steps {
                // Jenkins Credentials에 저장된 ID/PW(또는 PAT)를 환경변수로 꺼내옵니다.
                withCredentials([usernamePassword(
                    credentialsId: env.DOCKERHUB_CREDENTIALS_ID,
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    dir('monitoring/backend') {
                        // Gradle Jib task 실행 (파라미터로 계정 정보와 이미지 이름 전달)
                        sh '''
                        ./gradlew jib \
                            -Djib.to.image=docker.io/$DOCKERHUB_REPO:$IMAGE_TAG \
                            -Djib.to.auth.username=$DOCKER_USER \
                            -Djib.to.auth.password=$DOCKER_PASS \
                            -Djib.to.tags=latest
                        '''
                    }
                }
            }
        }

        stage('Deploy to Server') {
            steps {
                sshagent(['Monitoring_Backend_SSH']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no ubuntu@10.10.5.219 << 'EOF'
                            echo "--- 컨테이너 생성 시작 ---"
                            ./deploy.sh
                            echo "--- 컨테이너 생성 완료 ---"
EOF
                    '''
                }
            }
        }
    }
}