{
 "title": "Monitoring Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "전체 로그 타임라인",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"platform-backend\"}[1m]))"
    }
   ]
  },
  {
   "title": "ERROR 건수",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"platform-backend\"} | json | level=\"ERROR\" [1m]))"
    }
   ]
  },
  {
   "title": "전체 로그 리스트",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"platform-backend\"} | json"
    }
   ]
  },
  {
   "title": "BIZ 로그",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{job=\"platform-backend\"} | json | http_logType =~ \"BANK_RES|BANK_REQ|BANK_ERR|CONTROLLER_REQ|CONTROLLER_RES|CONTROLLER_ERR\""
    }
   ]
  },
  {
   "title": "BIZ 로그 건수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (http_logType) (count_over_time(\n  {job=\"platform-backend\"} | json | http_logType =~ \"BANK_REQ|BANK_RES|BANK_ERR|CONTROLLER_REQ|CONTROLLER_RES|CONTROLLER_ERR\" [1m]\n))"
    }
   ]
  }
 ]
}